plugins {
    id "org.hidetake.ssh" version "2.11.2"
}

remotes {
    host {
        host = '192.168.139.128'
        user = 'root'
        password = '123456'
    }
}

ssh.settings {
    knownHosts = allowAnyHosts
}

task check_local_curl {
    doLast {
        ssh.run {
            session(remotes.host) {
                println "--- CURL LOCALHOST ---"
                execute 'curl -I http://localhost:80/demo1 || true'
                execute 'curl -I http://localhost:80/ || true'
            }
        }
    }
}
